import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar_footer/navbar";
import Footer from "@/components/navbar_footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Work Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto lg:px-10`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
